### ISSUE TITLE
::selection pseudo selector breaks FireFox

### ISSUE THREAD

**Issue by ndugger** [rtsao/styletron#95] opened 2017-03-01 20:49 UTC
When I try to use the `::selection` pseudo selector via styletron, it works great in Chrome, but it breaks my entire site in Firefox. This is probably due to firefox not liking the selector, but that shouldn't just break the entire site.

An example of the offending code is as follows:

```
export const container = styled('div', () => ({
    userSelect: 'text',
    padding: '16px',
    lineHeight: '24px',
    fontSize: '15px',
    color: 'black',
    backgroundColor: 'white',

    // Breaks entire site in FF:
    '::selection': {
        color: 'white',
        backgroundColor: 'green'
    }
}
```

Firefox throws an error saying that it encountered an invalid or illegal string, but notes that the source of the error is "unknown". However, removing the `::selection` styles fixes the issue, leading me to believe that the cause is somewhere in styletron.

**Comment by rtsao** [comment] 2017-03-01 20:55
Yeah, this is a known issue (see: https://github.com/rtsao/styletron/issues/69) that needs to be fixed. I need to do some more investigation on the best way to solve this.

**Comment by rtsao** [comment] 2017-03-02 02:06
Marking as duplicate of https://github.com/rtsao/styletron/issues/69

**Closed by rtsao** 2017-03-02 02:06 UTC
Labels: duplicate
